### ISSUE TITLE
APIARY DOC

### ISSUE THREAD

**Issue by phenixiim** [lvasiliev/smstools-http-api#11]
Hi,
in the first way I would like to thank you for such great upgrade over smstools. 

I have prepared the APIARY doc for the API, maybe it will be handy for other users:
https://smstoolshttpapi.docs.apiary.io

Thanks again.

**Comment by lvasiliev** [comment]
Thanks! I added this link to the documentation.
https://github.com/lvasiliev/smstools-http-api/commit/489d3d650f0eaee90bd3bfb2c431cc8549f91945
