### ISSUE TITLE
Listing messages with different From header

### ISSUE THREAD

**Issue by mordae** [lvasiliev/smstools-http-api#3]
Hi, I had to remove [this check](https://github.com/lvasiliev/smstools-http-api/blob/master/app/api_1_0/smstools.py#L58) in our fork because:
- Incoming messages have `From` field indicating sender's phone number.
- Our auditing application needs to see all messages to stash them in a DB.
- All messages are listed, but only some can be accessed.

What is your use-case?

**Comment by lvasiliev** [comment]
I thought that in this case the incoming messages won't be available. 
I think, for your case need to create new ADMIN_ACCOUNTS variable:

```
if result['From'] == auth.username() or auth.username() in current_app.config['ADMIN_ACCOUNTS']:
    return jsonify(result)
else:
    return forbidden(None)
```

 In our use case, we provide access to smstools api and users from our company can send sms (monitoring, CI, etc). But we don't want if messages are read by other users.

**Comment by lvasiliev** [comment]
Why don't you write sms data to the database from smstools api? It's easier.

**Comment by mordae** [comment]
Perhaps, but `smstools-http-api` is a nice fit for our library system already and the auditing app is nicely decoupled from it.

**Comment by lvasiliev** [comment]
Now I add options ADMIN_ACCOUNTS for fix this issue.
