### ISSUE TITLE
Enhancement : Allow to delete SMS

### ISSUE THREAD

**Issue by tfagart** [lvasiliev/smstools-http-api#8]
Hello,

Thanks for this code. It works well. I would like to know whether you could add a REST method to delete/remove message, in incoming directory.

That will be something like this 
DELETE /api/v1.0/sms/<kind>/<string:message_id>

I'm willing to help, but i don't know very well how to code.

Regards

Thomas

**Comment by voileux** [comment]
I code for you this Enhancement 
this is the PR : https://github.com/lvasiliev/smstools-http-api/pull/9

**Comment by lvasiliev** [comment]
Thanks!
